CardRoll_Attack
/title="FULL ATTACK!"
/description="All your DICE get +1 ATTACK."
/texture_id=[4,1]
CardRoll_Defense
/title="DEFENSE! DEFENSE!"
/description="All your DICE get +1 HEALTH."
/texture_id=[4,2]
CardRoll_Doppelgeist
/title="DOPPELGEIST"
/description="Duplicates your GHOST DICE."
CardRoll_Exorcism
/title="EXORCISM"
/description="You won't gain any GHOST DICE after the next ROLL."
CardRoll_FakeNews
/title="FAKE NEWS"
/description="All JOURNALIST DICE multiply the ROLL SCORE by 0.5 instead of 2."
CardRoll_GhostHour
/title="GHOST HOUR"
/description="Your GHOST DICE' numbers add to your ROLL SCORE."
CardRoll_GraveRoll
/title="GRAVE ROLL"
/description="Your GHOST DICE will be rerolled."
CardRoll_HappyHour
/title="HAPPY HOUR"
/description="+2 to your ROLL MULTIPLIER."
/texture_id=[4,0]
CardRoll_Immortality
/title="IMMORTALITY"
/description="Your DICE cannot die during after the next ROLL."
CardRoll_MarketCrash
/title="MARKET CRASH"
/description="All INVESTOR DICE lose 50% of their savings."
CardRoll_Revenge
/title="REVENGE"
/description="If you have a lower ROLL SCORE than your antagonist, swap them."
CardRoll_Suidice
/title="SUIDICE"
/description="Your highest DIE explodes and eliminates all of your ANTAGONIST'S DICE."
CardRoll_WhiteElephant
/title="WHITE ELEPHANT"
/description="Your antagonist gets all your GHOST DICE of this ROLL."
/texture_id=[4,3]
CardRoll_TombRaider
/title="TOMB RAIDER"
/description="Steal one of your antagonist's GHOST DICE."
# DICE CARDS
CardDice_Assassin
/title="ASSASSIN"
/description="+2 ATTACK for this die."
/description2="When on [h]TOP FACE[h], +3 ATTACK for this die."
/texture_id=[1,1]
CardDice_Drunk
/title="DRUNK"
/description="This die attacks antagonist's dice regardless of their numbers."
/texture_id=[1,18]
CardDice_Tank
/title="TANK"
/description="+2 HEALTH for this die."
/description2="When on [h]TOP FACE[h], +1 HEALTH for surrounding dice."
/texture_id=[1,2]
CardDice_Antenna
/title="ANTENNA"
/description="Multiplies die's SCORE by the product of your other surviving dice with ANTENNA."
/texture_id=[1,4]
CardDice_Optimist
/title="OPTIMIST"
/description="This die only shows the numbers [h]4[h], [h]5[h], and [h]6[h]."
/description2="When on [h]TOP FACE[h], add the sum of your surviving dice greater or equal [h]4[h] to die's score."
/texture_id=[1,9]
CardDice_Pessimist
/title="PESSIMIST"
/description="This die only shows the numbers [h]1[h], [h]2[h], and [h]3[h]."
/description2="When on [h]TOP FACE[h], multiplies die's SCORE by the product of your surviving dice lower or equal [h]3[h]."
/texture_id=[1,8]
CardDice_General
/title="GENERAL"
/description="Multiplies die's SCORE by the number your surviving DICE."
/texture_id=[1,17]
CardDice_Journalist
/title="JOURNALIST"
/description="+2 ROLL MULTIPLIER."
/texture_id=[1,6]
CardDice_Influencer
/title="INFLUENCER"
# /description1="---"
/description2="When on [h]TOP FACE[h], creates a ROLL CARD."
/texture_id=[1,7]
CardDice_Engineer
/title="ENGINEER"
# /description="---"
/description2="When on [h]TOP FACE[h], creates a DICE CARD."
/texture_id=[1,14]
CardDice_Medium
/title="MEDIUM"
/description="Adds the number of GHOST DICE to die's SCORE."
/texture_id=[1,15]
CardDice_PlusOne
/title="PLUS ONE"
/description="+1 to die's SCORE"
/description2="When on [h]TOP FACE[h], +1 to die's SCORE for each of your surviving DICE."
/texture_id=[1,5]
CardDice_Investor
/title="INVESTOR"
/description="Adds die's SCORE with 10% interest to SAVINGS (currently %VAR1_F)."
/description2="When on [h]TOP FACE[h], adds die's SAVINGS to the ROLL SCORE and reset SAVINGS to 0."
/texture_id=[1,3]
CardDice_PowerDice
/title="POWER UP"
/description="This die multiplies its score by [h]%VAR1[h]."
/description2="When on [h]TOP FACE[h], increase the factor by 1."
/texture_id=[1,16]
CardDice_ShortSighted
/title="SHORT-SIGHTED"
/description="Attacks farthest antagonist's die regardless of its number."
CardDice_Historian
/title="HISTORIAN"
/description="Gains permanently +1 SCORE when alive and activating a ROLL CARD (currently %VAR1)."
/texture_id=[1,13]
CardDice_Librarian
/title="LIBRARIAN"
/description="Gains permanently +1 SCORE when alive and assigning a DICE CARD to another die (currently %VAR1)."
/texture_id=[1,12]
CardDice_Researcher
/title="RESEARCHER"
/description="Gains permanently +1 ROLL MULTIPLIER when alive and activating a CYCLE CARD (currently %VAR1)."
/texture_id=[1,10]
CardDice_Veteran
/title="VETERAN"
/description="This die gains +2 SCORE each time it survives a roll (currently %VAR1). Resets to 0 when it dies."
CardDice_WarHero
/title="WAR HERO"
/description="This die gains +1 SCORE each time it kills another die (currently [h]%VAR1[h])."
CardDice_Train
/title="TRAIN"
/description="Adds the sum of your other dice higher than this die to its score."
/texture_id=[1,11]
# CYCLE CARDS
CardCycle_ExtraDie
/title="EXTRA DIE"
/description="+1 DIE to your army."
CardCycle_EternalRoll
/title="ETERNAL ROLL"
/description="Your ROLL CARDS' lifetime increases by 1 ROLL."
CardCycle_GhostDiscount
/title="GHOST DISCOUNT"
/description="After scoring a combination, you'll get one GHOST DIE back (MAX. 4)."
CardCycle_Graveyard
/title="GRAVEYARD"
/description="+2 SPACES for GHOST DICE."
CardCycle_Supermarket
/title="SUPERMARKET"
/description="+1 CARD is shown after scoring a combination."
CardCycle_Recycle
/title="RECYCLE"
/description="You can redraw the CARDS SELECTION after scoring combinations by using GHOST DICE."
