CardRoll_Attack
/title="FULL ATTACK!"
/description="All your DICE get +1 ATTACK."
CardRoll_Defense
/title="DEFENSE! DEFENSE!"
/description="All your DICE get +1 HEALTH."
CardRoll_Doppelgeist
/title="DOPPELGEIST"
/description="Duplicates your GHOST DICE."
CardRoll_Exorcism
/title="EXORCISM"
/description="You won't gain any GHOST DICE this ROLL."
CardRoll_FakeNews
/title="FAKE NEWS"
/description="All JOURNALIST DICE multiply the ROLL SCORE by 0.5 instead of 2."
CardRoll_GhostHour
/title="GHOST HOUR"
/description="Your GHOST DICE' numbers add to your ROLL SCORE."
CardRoll_GraveRoll
/title="GRAVE ROLL"
/description="Your GHOST DICE will be rerolled."
CardRoll_HappyHour
/title="HAPPY HOUR"
/description="+2 to your ROLL MULTIPLIER."
CardRoll_Immortality
/title="IMMORTALITY"
/description="Your DICE cannot die during this ROLL."
CardRoll_MarketCrash
/title="MARKET CRASH"
/description="All INVESTOR DICE lose 50% of their savings."
CardRoll_Revenge
/title="REVENGE"
/description="If you have a lower ROLL SCORE than your antagonist, swap them."
CardRoll_Suidice
/title="SUIDICE"
/description="Your highest DIE explodes and eliminates all of your ANTAGONIST'S DICE."
CardRoll_WhiteElephant
/title="WHITE ELEPHANT"
/description="Your antagonist gets all your GHOST DICE of this ROLL."
CardRoll_TombRaider
/title="TOMB RAIDER"
/description="Steal one of your antagonist's GHOST DICE."
# DICE CARDS
CardDice_Assassin
/title="ASSASSIN"
/description="+2 ATTACK"
/description2="When [h]ACTIVE[h], attacks ANTAGONIST's highest die."
/texture_id=[1,1]
CardDice_Blind
/title="BLIND"
/description="Attacks closest antagonist's die regardless of its number."
CardDice_Tank
/title="TANK"
/description="+2 HEALTH"
/description2="When [h]ACTIVE[h], +1 HEALTH for surrounding dice."
/texture_id=[1,2]
CardDice_Antenna
/title="ANTENNA"
/description="Multiplies its SCORE by the product of your other surviving dice with ANTENNA."
/texture_id=[1,4]
CardDice_Optimist
/title="OPTIMIST"
/description="This die only shows the numbers [h]4[h], [h]5[h], and [h]6[h]."
/description2="When [h]ACTIVE[h], scores additionally the sum of your surviving dice greater or equal [h]4[h]."
/texture_id=[1,9]
CardDice_Pessimist
/title="PESSIMIST"
/description="This die only shows the numbers [h]1[h], [h]2[h], and [h]3[h]."
/description2="When [h]ACTIVE[h], multiplies its SCORE by the product of your surviving dice lower or equal [h]3[h]."
/texture_id=[1,8]
CardDice_General
/title="GENERAL"
/description="Adds the sum of your surviving DICE to its SCORE."
CardDice_Journalist
/title="JOURNALIST"
/description="+2 ROLL MULTIPLIER."
/texture_id=[1,6]
CardDice_Influencer
/title="INFLUENCER"
# /description1="---"
/description2="When [h]ACTIVE[h], creates a ROLL CARD."
/texture_id=[1,7]
CardDice_Engineer
/title="ENGINEER"
# /description="---"
/description2="When [h]ACTIVE[h], creates a DICE CARD."
CardDice_Medium
/title="MEDIUM"
/description="Adds number of your GHOST DICE to its SCORE."
CardDice_PlusOne
/title="PLUS ONE"
/description="+1 to its SCORE"
/description2="When [h]ACTIVE[h], +1 to its SCORE for each friendly, surviving DICE."
/texture_id=[1,5]
CardDice_Investor
/title="INVESTOR"
/description="Saves its own SCORE with 10% interest."
/description2="When [h]ACTIVE[h], adds its SAVINGS to the ROLL SCORE."
/texture_id=[1,3]
CardDice_PowerDice
/title="POWER UP"
/description="Multiply dice's SCORE with its own SCORE again."
CardDice_ShortSighted
/title="SHORT-SIGHTED"
/description="Attacks farthest antagonist's dice regardless of its number."
CardDice_Historian
/title="HISTORIAN"
/description="Gains +1 SCORE when alive and activating a ROLL CARD."
/texture_id=[1,13]
CardDice_Librarian
/title="LIBRARIAN"
/description="Gains +1 SCORE when alive and assigning DICE CARD."
/texture_id=[1,12]
CardDice_Researcher
/title="RESEARCHER"
/description="Gains +1 ROLL MULTIPLIER when alive and activating a CYCLE CARD."
/texture_id=[1,10]
CardDice_Train
/title="TRAIN"
/description="Add numbers of your other dice higher than itself to the SCORE."
/texture_id=[1,11]
# CYCLE CARDS
CardCycle_ExtraDice
/title="EXTRA DICE"
/description="Add +1 DICE to your army."
CardCycle_EternalRoll
/title="ETERNAL ROLL"
/description="Your ROLL CARDS' lifetime increases by 1 ROLL."
CardCycle_GhostDiscount
/title="GHOST DISCOUNT"
/description="When scoring a combination, you'll get one GHOST DICE back (MAX. 4)."
CardCycle_Graveyard
/title="GRAVEYARD"
/description="+1 SPACE for GHOST DICE."
