CardRoll_Attack
/title="FULL ATTACK!"
/description="All your dices get +1 ATTACK."
CardRoll_Defense
/title="DEFENSE! DEFENSE!"
/description="All your dices get +1 HEALTH."
CardRoll_Doppelgeist
/title="DOPPELGEIST"
/description="Duplicates your GHOST DICES."
CardRoll_Exorcism
/title="EXORCISM"
/description="You won't gain any GHOST DICES this ROLL."
CardRoll_FakeNews
/title="FAKE NEWS"
/description="All JOURNALIST DICES multiply the ROLL SCORE by 0.5 instead of 2."
CardRoll_GhostHour
/title="GHOST HOUR"
/description="Your GHOST DICES' numbers add to your ROLL SCORE."
CardRoll_GraveRoll
/title="GRAVE ROLL"
/description="Your GHOST DICES will be rerolled."
CardRoll_HappyHour
/title="HAPPY HOUR"
/description="X2 your ROLL SCORE."
CardRoll_Immortality
/title="IMMORTALITY"
/description="Your DICES cannot die during this ROLL."
CardRoll_MarketCrash
/title="MARKET CRASH"
/description="All INVESTOR DICES lose 50%%%% of their savings."
CardRoll_Revenge
/title="REVENGE"
/description="If you have a lower ROLL SCORE than your antagonist, swap them."
CardRoll_Suidice
/title="SUIDICE"
/description="Your DICE with the highest number explodes and eliminates all of your ANTAGONIST'S DICES."
CardRoll_WhiteElephant
/title="WHITE ELEPHANT"
/description="Your antagonist gets all your GHOST DICES of this ROLL."
CardRoll_TombRaider
/title="TOMB RAIDER"
/description="Steal one of your antagonist's GHOST DICES."
CardDice_Assassin
/title="ASSASSIN"
/description="Gets +2 ATTACK at start of each ROLL."
CardDice_Tank
/title="TANK"
/description="Gets +2 HEALTH at start of each ROLL."
CardDice_Antenna
/title="ANTENNA"
/description="Multiply dice's SCORE with the SCORE of other dices with ANTENNA."
CardDice_Optimist
/title="OPTIMIST"
/description="All sides of this dices show one number higher (max. 6)."
CardDice_Pessimist
/title="PESSIMIST"
/description="All sides of this dices show one number lower (min. 1)."
CardDice_General
/title="GENERAL"
/description="Adds number of your surviving DICES to its SCORE."
CardDice_Journalist
/title="JOURNALIST"
/description="X2 your ROLL SCORE."
CardDice_Influencer
/title="INFLUENCER"
/description="Create a ROLL CARD if it survives and shows a 1."
CardDice_Engineer
/title="ENGINEER"
/description="Create a DICE CARD if it survives and shows a 1."
CardDice_Medium
/title="MEDIUM"
/description="Adds number of your GHOST DICES to its SCORE."
CardDice_Investor
/title="INVESTOR"
/description="Saves its own SCORE when surviving with 10%%%% interest. Pay out when showing a 1."
CardDice_PowerDice
/title="POWER UP"
/description="Multiply dice's SCORE with its own SCORE again."
CardDice_ShortSighted
/title="SHORT-SIGHTED"
/description="Attacks farthest antagonist's dice regardless of its number."
CardDice_Blind
/title="BLIND"
/description="Attacks closest antagonist's dice regardless of its number."
CardDice_Historian
/title="HISTORIAN"
/description="Gains +1 SCORE when alive and activating a ROLL CARD."
CardDice_Librarian
/title="LIBRARIAN"
/description="Gains +1 SCORE when alive and assigning DICE CARD."
CardCycle_ExtraDice
/title="EXTRA DICE"
/description="Add +1 DICE to your army."
CardCycle_EternalRoll
/title="ETERNAL ROLL"
/description="Your ROLL CARDS' lifetime increases by 1 ROLL."
CardCycle_Graveyard
/title="GRAVEYARD"
/description="+1 SPACE for GHOST DICES."
